import { useEffect, useState } from 'react';
import { supabase } from '../../services/supabase';
import './WorkflowPanels.css';

export default function AdminSettings({user}) {
  const [profiles,setProfiles]=useState([]),[settings,setSettings]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;Promise.all([supabase.from('profiles').select('id,full_name,role').order('full_name'),supabase.from('restaurant_settings').select('*').eq('id',true).single()]).then(([people,config])=>{if(!active)return;if(people.error||config.error)setError((people.error||config.error).message);else{setProfiles(people.data);setSettings(config.data);}});return()=>{active=false;};},[]);
  const assign=async(id,role)=>{setBusy(true);setError('');const {error:failure}=await supabase.rpc('assign_user_role',{p_user_id:id,p_role:role});if(failure)setError(failure.message);else{setProfiles(rows=>rows.map(row=>row.id===id?{...row,role}:row));setNotice('Role updated. It takes effect in the user’s next session.');}setBusy(false);};
  const save=async e=>{e.preventDefault();setBusy(true);setError('');let faq;try{faq=typeof settings.faq==='string'?JSON.parse(settings.faq):settings.faq;if(!faq||Array.isArray(faq)||typeof faq!=='object')throw new Error('Enter FAQs as a JSON object.');}catch(failure){setError(failure.message);setBusy(false);return;}const {error:failure}=await supabase.from('restaurant_settings').update({restaurant_name:settings.restaurant_name,operating_hours:settings.operating_hours,vat_registered:settings.vat_registered,faq}).eq('id',true);if(failure)setError(failure.message);else setNotice('Restaurant settings saved. Updated knowledge will be indexed by the next batch.');setBusy(false);};
  return <div className="page-content workflow"><div className="page-hero"><div><h2 className="page-title">Administration</h2><p className="page-sub">Manage account roles and approved restaurant information.</p></div></div>{error&&<p role="alert" className="workflow-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {settings&&<form className="workflow-section" onSubmit={save}><h3>Restaurant settings</h3><div className="workflow-controls"><label>Restaurant name<input required value={settings.restaurant_name} onChange={e=>setSettings({...settings,restaurant_name:e.target.value})}/></label><label>Operating hours<input required value={settings.operating_hours} onChange={e=>setSettings({...settings,operating_hours:e.target.value})}/></label><label>Tax treatment<select value={String(settings.vat_registered)} onChange={e=>setSettings({...settings,vat_registered:e.target.value==='true'})}><option value="false">Non-VAT registered</option><option value="true">VAT registered · prices include 12% VAT</option></select></label></div><label>Approved FAQs (JSON object)<textarea rows={5} value={typeof settings.faq==='string'?settings.faq:JSON.stringify(settings.faq,null,2)} onChange={e=>setSettings({...settings,faq:e.target.value})}/></label><p className="workflow-note">Tax treatment controls the eligible portion of staff-approved senior/PWD discounts. Confirm this setting against the restaurant’s registration.</p><button className="hero-btn" disabled={busy}>Save settings</button></form>}
    <section className="workflow-section"><h3>User roles</h3><p>Accounts are created through sign-up. Only administrators can assign elevated roles.</p>{profiles.map(profile=><div className="workflow-table-row" key={profile.id}><span>{profile.full_name}{profile.id===user.id?' (you)':''}</span><label><span className="sr-only">Role for {profile.full_name}</span><select disabled={busy||profile.id===user.id} value={profile.role} onChange={e=>assign(profile.id,e.target.value)}>{['customer','staff','cashier','kitchen','management','admin'].map(role=><option key={role} value={role}>{role}</option>)}</select></label></div>)}</section>
  </div>;
}
